### ISSUE TITLE
trouble pip installing, Python 3.4.3

### ISSUE THREAD

**Issue by cavaunpeu** [akelleh/causality#10]
```
$ sudo pip install causality

The directory '/Users/me/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/me/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting causality
  Downloading causality-0.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-zarx22qb/causality/setup.py", line 6, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/Users/me/.virtualenvs/shopkeep/lib/python3.4/codecs.py", line 891, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/pip-build-zarx22qb/causality/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-zarx22qb/causality
```

**Comment by akelleh** [comment]
Hi Will!  Did you try the -H flag?

sudo -H pip install causality

Although I'd always recommend installing in a virtualenv!

On Mon, Jan 25, 2016 at 4:12 PM, William Wolf <notifications@github.com>
wrote:

> $ sudo pip install causality
>
> The directory '/Users/me/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> The directory '/Users/me/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Collecting causality
>   Downloading causality-0.0.1.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/tmp/pip-build-zarx22qb/causality/setup.py", line 6, in <module>
>         with open(path.join(here, 'README.md'), encoding='utf-8') as f:
>       File "/Users/me/.virtualenvs/shopkeep/lib/python3.4/codecs.py", line 891, in open
>         file = builtins.open(filename, mode, buffering)
>     FileNotFoundError: [Errno 2] No such file or directory: '/private/tmp/pip-build-zarx22qb/causality/README.md'
>
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-zarx22qb/causality
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akelleh/causality/issues/10>.
>



-- 

Adam Kelleher | BuzzFeed | Sr. Data Scientist | (843) 737-1257 | tw:
@akelleh
200 Fifth Ave. 8th Floor, NY, NY 10010

**Comment by cavaunpeu** [comment]
same error! am installing into a virtualenv (using pyenv, and
virtualenvwrapper) as well.

On Mon, Jan 25, 2016 at 3:52 PM, Adam Kelleher <notifications@github.com>
wrote:

> Hi Will! Did you try the -H flag?
>
> sudo -H pip install causality
>
> Although I'd always recommend installing in a virtualenv!
>
> On Mon, Jan 25, 2016 at 4:12 PM, William Wolf <notifications@github.com>
> wrote:
>
> > $ sudo pip install causality
> >
> > The directory '/Users/me/Library/Caches/pip/http' or its parent
> directory is not owned by the current user and the cache has been disabled.
> Please check the permissions and owner of that directory. If executing pip
> with sudo, you may want sudo's -H flag.
> > The directory '/Users/me/Library/Caches/pip' or its parent directory is
> not owned by the current user and caching wheels has been disabled. check
> the permissions and owner of that directory. If executing pip with sudo,
> you may want sudo's -H flag.
> > Collecting causality
> > Downloading causality-0.0.1.tar.gz
> > Complete output from command python setup.py egg_info:
> > Traceback (most recent call last):
> > File "<string>", line 1, in <module>
> > File "/private/tmp/pip-build-zarx22qb/causality/setup.py", line 6, in
> <module>
> > with open(path.join(here, 'README.md'), encoding='utf-8') as f:
> > File "/Users/me/.virtualenvs/shopkeep/lib/python3.4/codecs.py", line
> 891, in open
> > file = builtins.open(filename, mode, buffering)
> > FileNotFoundError: [Errno 2] No such file or directory:
> '/private/tmp/pip-build-zarx22qb/causality/README.md'
> >
> > ----------------------------------------
> > Command "python setup.py egg_info" failed with error code 1 in
> /private/tmp/pip-build-zarx22qb/causality
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/akelleh/causality/issues/10>.
> >
>
>
>
> --
>
> Adam Kelleher | BuzzFeed | Sr. Data Scientist | (843) 737-1257 | tw:
> @akelleh
> 200 Fifth Ave. 8th Floor, NY, NY 10010
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akelleh/causality/issues/10#issuecomment-174681745>.
>



-- 


William Wolf

Data Scientist



ShopKeep | 800.820.9814 <8008209814;>


shopkeep.com | facebook <https://www.facebook.com/ShopKeepPOS> twitter
<https://twitter.com/shopkeep> linkedin
<http://www.linkedin.com/company/shopkeep-pos>

**Comment by akelleh** [comment]
I see! Must be an issue with the .tar.gz file.  Can you set it to install
from the wheel as a workaround while i get it fixed?

-Adam

On Mon, Jan 25, 2016 at 4:54 PM, William Wolf <notifications@github.com>
wrote:

> same error! am installing into a virtualenv (using pyenv, and
> virtualenvwrapper) as well.
>
> On Mon, Jan 25, 2016 at 3:52 PM, Adam Kelleher <notifications@github.com>
> wrote:
>
> > Hi Will! Did you try the -H flag?
> >
> > sudo -H pip install causality
> >
> > Although I'd always recommend installing in a virtualenv!
> >
> > On Mon, Jan 25, 2016 at 4:12 PM, William Wolf <notifications@github.com>
> > wrote:
> >
> > > $ sudo pip install causality
> > >
> > > The directory '/Users/me/Library/Caches/pip/http' or its parent
> > directory is not owned by the current user and the cache has been
> disabled.
> > Please check the permissions and owner of that directory. If executing
> pip
> > with sudo, you may want sudo's -H flag.
> > > The directory '/Users/me/Library/Caches/pip' or its parent directory is
> > not owned by the current user and caching wheels has been disabled. check
> > the permissions and owner of that directory. If executing pip with sudo,
> > you may want sudo's -H flag.
> > > Collecting causality
> > > Downloading causality-0.0.1.tar.gz
> > > Complete output from command python setup.py egg_info:
> > > Traceback (most recent call last):
> > > File "<string>", line 1, in <module>
> > > File "/private/tmp/pip-build-zarx22qb/causality/setup.py", line 6, in
> > <module>
> > > with open(path.join(here, 'README.md'), encoding='utf-8') as f:
> > > File "/Users/me/.virtualenvs/shopkeep/lib/python3.4/codecs.py", line
> > 891, in open
> > > file = builtins.open(filename, mode, buffering)
> > > FileNotFoundError: [Errno 2] No such file or directory:
> > '/private/tmp/pip-build-zarx22qb/causality/README.md'
> > >
> > > ----------------------------------------
> > > Command "python setup.py egg_info" failed with error code 1 in
> > /private/tmp/pip-build-zarx22qb/causality
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/akelleh/causality/issues/10>.
> > >
> >
> >
> >
> > --
> >
> > Adam Kelleher | BuzzFeed | Sr. Data Scientist | (843) 737-1257 | tw:
> > @akelleh
> > 200 Fifth Ave. 8th Floor, NY, NY 10010
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/akelleh/causality/issues/10#issuecomment-174681745>.
> >
>
>
>
> --
>
>
> William Wolf
>
> Data Scientist
>
>
>
> ShopKeep | 800.820.9814 <8008209814;>
>
>
> shopkeep.com | facebook <https://www.facebook.com/ShopKeepPOS> twitter
> <https://twitter.com/shopkeep> linkedin
> <http://www.linkedin.com/company/shopkeep-pos>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akelleh/causality/issues/10#issuecomment-174683042>.
>



-- 

Adam Kelleher | BuzzFeed | Sr. Data Scientist | (843) 737-1257 | tw:
@akelleh
200 Fifth Ave. 8th Floor, NY, NY 10010

**Comment by akelleh** [comment]
hey will,

it should be fixed now!  mind giving it a try?

best,
Adam

On Mon, Jan 25, 2016 at 4:56 PM, Adam Kelleher <adam.kelleher@buzzfeed.com>
wrote:

> I see! Must be an issue with the .tar.gz file.  Can you set it to install
> from the wheel as a workaround while i get it fixed?
>
> -Adam
>
> On Mon, Jan 25, 2016 at 4:54 PM, William Wolf <notifications@github.com>
> wrote:
>
>> same error! am installing into a virtualenv (using pyenv, and
>> virtualenvwrapper) as well.
>>
>> On Mon, Jan 25, 2016 at 3:52 PM, Adam Kelleher <notifications@github.com>
>> wrote:
>>
>> > Hi Will! Did you try the -H flag?
>> >
>> > sudo -H pip install causality
>> >
>> > Although I'd always recommend installing in a virtualenv!
>> >
>> > On Mon, Jan 25, 2016 at 4:12 PM, William Wolf <notifications@github.com
>> >
>> > wrote:
>> >
>> > > $ sudo pip install causality
>> > >
>> > > The directory '/Users/me/Library/Caches/pip/http' or its parent
>> > directory is not owned by the current user and the cache has been
>> disabled.
>> > Please check the permissions and owner of that directory. If executing
>> pip
>> > with sudo, you may want sudo's -H flag.
>> > > The directory '/Users/me/Library/Caches/pip' or its parent directory
>> is
>> > not owned by the current user and caching wheels has been disabled.
>> check
>> > the permissions and owner of that directory. If executing pip with sudo,
>> > you may want sudo's -H flag.
>> > > Collecting causality
>> > > Downloading causality-0.0.1.tar.gz
>> > > Complete output from command python setup.py egg_info:
>> > > Traceback (most recent call last):
>> > > File "<string>", line 1, in <module>
>> > > File "/private/tmp/pip-build-zarx22qb/causality/setup.py", line 6, in
>> > <module>
>> > > with open(path.join(here, 'README.md'), encoding='utf-8') as f:
>> > > File "/Users/me/.virtualenvs/shopkeep/lib/python3.4/codecs.py", line
>> > 891, in open
>> > > file = builtins.open(filename, mode, buffering)
>> > > FileNotFoundError: [Errno 2] No such file or directory:
>> > '/private/tmp/pip-build-zarx22qb/causality/README.md'
>> > >
>> > > ----------------------------------------
>> > > Command "python setup.py egg_info" failed with error code 1 in
>> > /private/tmp/pip-build-zarx22qb/causality
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/akelleh/causality/issues/10>.
>> > >
>> >
>> >
>> >
>> > --
>> >
>> > Adam Kelleher | BuzzFeed | Sr. Data Scientist | (843) 737-1257 | tw:
>> > @akelleh
>> > 200 Fifth Ave. 8th Floor, NY, NY 10010
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/akelleh/causality/issues/10#issuecomment-174681745
>> >.
>> >
>>
>>
>>
>> --
>>
>>
>> William Wolf
>>
>> Data Scientist
>>
>>
>>
>> ShopKeep | 800.820.9814 <8008209814;>
>>
>>
>> shopkeep.com | facebook <https://www.facebook.com/ShopKeepPOS> twitter
>> <https://twitter.com/shopkeep> linkedin
>> <http://www.linkedin.com/company/shopkeep-pos>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/akelleh/causality/issues/10#issuecomment-174683042>.
>>
>
>
>
> --
>
> Adam Kelleher | BuzzFeed | Sr. Data Scientist | (843) 737-1257 | tw:
> @akelleh
> 200 Fifth Ave. 8th Floor, NY, NY 10010
>
>


-- 

Adam Kelleher | BuzzFeed | Sr. Data Scientist | (843) 737-1257 | tw:
@akelleh
200 Fifth Ave. 8th Floor, NY, NY 10010

**Comment by cavaunpeu** [comment]
success!

**Comment by akelleh** [comment]
Awesome!  Thanks for reporting this, Will!

On Mon, Jan 25, 2016 at 5:41 PM, William Wolf <notifications@github.com>
wrote:

> success!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/akelleh/causality/issues/10#issuecomment-174705417>.
>



-- 

Adam Kelleher | BuzzFeed | Sr. Data Scientist | (843) 737-1257 | tw:
@akelleh
200 Fifth Ave. 8th Floor, NY, NY 10010

**Comment by cavaunpeu** [comment]
pleasure!
