### ISSUE TITLE
list of improvements to be made

### ISSUE THREAD

**Issue by themantalope** [akelleh/causality#23]
I see that there is a list of notes for improvements at the bottom of the readme, is there any file in the repo that shows what is left to do? I can take a look at some of the remaining methods to be implemented.

**Comment by akelleh** [comment]
That would be excellent!  I'll update the list this weekend.

**Comment by akelleh** [comment]
i've created a sprint in JIRA 
https://causality.atlassian.net/secure/RapidBoard.jspa?rapidView=1

Pick up an issue and let's get into it!

We'll have discussions about details on the pull requests.  When you pick up an issue, we can work out the details of the interface, where the code lives, and the implementation.  Just start a trivial PR to kick off the conversation.

**Comment by akelleh** [comment]
send me your email and ill add you as a user

**Comment by themantalope** [comment]
Sure, use my email associated with my GitHub account.

**Comment by themantalope** [comment]
@akelleh is there a way I can PM you my email address?

**Comment by akelleh** [comment]
want me to use the gmail one on your profile page?

**Comment by themantalope** [comment]
yep that's fine

**Comment by akelleh** [comment]
invite sent!

**Comment by light44** [comment]
A graph of causal factors led me here. Can I get an invite?

**Comment by akelleh** [comment]
lol. Of course!

**Comment by light44** [comment]
Give me a day to grok your package (giggity), then I'll jump into one of the four issues up on the atlassian board.
