### ISSUE TITLE
networkx version problem?

### ISSUE THREAD

**Issue by jeroenbouwman** [akelleh/causality#44]
I am trying to run the example given at the causality main github page but I run into the following problem: 

Traceback (most recent call last):

  File "<ipython-input-1-518722c8d69f>", line 25, in <module>
    graph = ic_algorithm.search(X, variable_types)

  File "...../causality/inference/search/__init__.py", line 26, in search
    self._find_skeleton(data, variable_types)

  File "......./causality/inference/search/__init__.py", line 126, in _find_skeleton
    z_candidates = list(set(x_neighbors + y_neighbors) - set([x,y]))

TypeError: unsupported operand type(s) for +: 'dict_keyiterator' and 'dict_keyiterator'

The x_neighbor and y_neighbors are variables returned by the networkx.Graph.neighbors function which returns an iterator over all neighbors of node n. At least for version 2.0 as is specified  by the requirements.txt. For earlier versions (e.g. 1.10) this function returns a list of nodes that are adjacent to n. Can it be that the causality package only runs with version 1.10 of networkx and not the 2.0 verson?

thanks for the help,
Jeroen

**Comment by frmsaul** [comment]
The [most recent commit](https://github.com/akelleh/causality/commit/282ea282751c1d4146296a3c03d621eff5677a85) solves your issue. I don't think it was pushed to pypi yet (@akelleh, do you know?). You could either solve it by installing from source or use an earlier version of `networkx`.

Saul

**Comment by akelleh** [comment]
Not yet! I'll get on that tonight.

**Comment by akelleh** [comment]
should be resolved! upgrade to causality-0.0.5
