### ISSUE TITLE
Doesn't install for Python3

### ISSUE THREAD

**Issue by fedorzh** [akelleh/causality#63]
I tried to install it for Python 3, but wasn't able to as the package depends on `pymc`, and even though I have `pymc3` installed, doesn't connect to that one instead

**Comment by akelleh** [comment]
oof, we had an upgrade issue on the to-do list. I'll have to boost its priority. Thanks for reporting!

**Comment by akelleh** [comment]
I'll close this one and prioritize the "Transition to pymc3" issue.
