### ISSUE TITLE
Causality installation error (cephes?)

### ISSUE THREAD

**Issue by dreinstein10** [akelleh/causality#67]
Hi, 
First of all, I'm still learning python so this might be an obvious question, but I wanted to try this library out and I tried to install causality using pip but I got an error that I think is related to a dependency called **chephes**, please see the image attached.

![screen shot 2018-07-14 at 10 33 00 pm](https://user-images.githubusercontent.com/13284418/42730708-9cbd427a-87b8-11e8-8d7a-2f08640f2e02.png)

How do I install chephes? Am I missing something?
Thanks in advance

**Comment by morenoh149** [comment]
I too cannot install https://github.com/akelleh/causality/issues/68

**Comment by akelleh** [comment]
Upgrade to pymc3 will hopefully resolve this one! I'll get on that today.

**Comment by akelleh** [comment]
removed the dependency in the meantime.
