### ISSUE TITLE
Interpretation of edges in causal graph inference

### ISSUE THREAD

**Issue by jjtwwdei** [akelleh/causality#77]
I have some results like edge ('x2', 'x4', {'arrows': ['x2', 'x2', 'x4' ], 'marked': False}) when I test with the causal graph inference. How do I interpret the issue? Does this mean its a undirected edge like ('x2', 'x4', {'arrows': [], 'marked': False}).

**Comment by akelleh** [comment]
This was a bug which I believe has been resolved! Please let me know if you still find otherwise.
